GET http://localhost:8080/api/student

###
GET  http://localhost:8080/api/student/1



###
POST http://localhost:8080/api/student
Content-Type: application/json


{
    "name":"Shreya",
   "currentClass":12,
   "division":"B"
    

}

###

PUT http://localhost:8080/api/student/1
Content-Type: application/json


{
    "name":"Riya",
   "currentClass":10,
   "division":"A"
} 

###
DELETE  http://localhost:8080/api/student/1